### ISSUE TITLE
pusher motor interaction with switches and firmware

### ISSUE THREAD

**Issue by bmarks-mylo** [projectfdl/FDL-3-Blaster#4]
Looking at the pusher design and reading through the latest firmware I'm not sure I understand the interaction with the front/rear pusher switches and motor control.  I think I'm seeing that there is a  forward and reverse control circuit for the pusher motor but I can't seem to find where the firmware is using both directions.  

Can you please give a brief explanation of the interaction of these components and the firmware?

**Comment by bmarks-mylo** [comment]
Ok, I think I understand now.  The circuit acts as a brake to stop the motor from spinning faster.

My only remaining question is then why the need for a front and rear switch.  Why is knowing that the plunger is fully forward important?  Just a way to time it?

**Comment by projectfdl** [comment]
The front switch is an indication that a full forward cycle has occured. From that point there is a short brake blip to slow it down and coast to the rear position if you are on your final shot. It is both timing and a self test. There is no reverse direction as that would require a full instead of half hbridge for minimal gain aside from maybe backing the pusher out in a jam like the original FDL-2 used to.

**Comment by bmarks-mylo** [comment]
Excellent, thank you for the information.
