### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by xoxota99** [projectfdl/FDL-3-Blaster#7]
Not sure where to ask these questions:
- What material should I use when printing these parts? PLA? PETG?
- What's the difference between the pusher, and the "Pusher 1mm dwell"?

**Comment by 43sunsets** [comment]
1. You can use whatever you like. PLA is the easiest to print with but vulnerable to heat -- try not to leave it in a hot car, or your parts may end up warped. PETG is still easy to print but has slightly better heat resistance. ABS is harder to print (typically requires an enclosure) and gives off noxious/toxic fumes, but is lighter and potentially stronger, and has much better heat resistance. 

I personally print with PLA+, which is significantly stronger than regular PLA.

2. The pusher with 1mm dwell was an experimental part made in an attempt to resolve problems with the auto pusher intermittently coming to a rest partially extended, instead of being fully retracted. As far as I can tell the latest v1.04 firmware has now fixed the intermittent pusher retraction problem, so there's no need to use the test pusher with the extra dwell time. Just use the regular pusher.
